SSE 피드백 받는 기능 구현(#84)
JongHyeok-Park/kmu-toktok-admin-react pull request #86
Opened 2024-12-02 06:30 UTC by thanhhien234

### 🔍 개요

SSE 피드백 받는 기능 구현
### ✨ 작업 내용

- 피드백 도착할 때까지 로딩 뜸
- EventSource로 피드백 데이터를 받도록 구현

### ✅ 체크리스트

- [x] 코드가 제대로 빌드되는지 확인했습니다.
- [x] 문서(예: README, API 문서)가 업데이트되었거나 업데이트가 필요하지 않습니다.
- [x] PR에 연결된 이슈가 있는 경우, 해당 이슈 번호를 링크했습니다.

### 🔗 관련 이슈

closed #84

2024-12-02 06:47 UTC, JongHyeok-Park requested changes

2024-12-02 06:47 UTC, JongHyeok-Park commented on src/routes/Testing/hooks/useTesting.js
> +      setIsLoading(false);
이거 `setIsLoading(false);` 부분을 onopen일 때 하면 안되나요? 저렇게 불필요한 라인이 계속 호출되는 것 같은데

2024-12-02 07:46 UTC, thanhhien234 commented on src/routes/Testing/hooks/useTesting.js
> +      setIsLoading(false);
수정했어요

2024-12-03 07:29 UTC, JongHyeok-Park approved these changes

2024-12-03 07:29 UTC, merged